---
deployment:
  tasks:
    # Set deployment target (public_html/groupProject)
    - export DEPLOYDIR=/home/silversu/public_html/groupProject

    # Create the directory if it doesn't exist
    - /bin/mkdir -p $DEPLOYDIR

    # Sync everything from the repo to the deployment dir
    - /usr/bin/rsync -a --delete --exclude='.git*' ./ $DEPLOYDIR/
