---
deployment:
  tasks:
    # Targets
    - export WEBROOT=/home/silversu/public_html
    - export GROUPDIR=$WEBROOT/group

    # Ensure target dirs exist
    - /bin/mkdir -p $GROUPDIR

    # Deploy site root (groupProject/index.html -> https://isakloke.se/)
    - /usr/bin/rsync -a --delete --exclude='.git*' index.html $WEBROOT/

    # Deploy /group (groupProject/group/* -> https://isakloke.se/group)
    - /usr/bin/rsync -a --delete --exclude='.git*' group/ $GROUPDIR/
